Document: nonfree-touchscreen-firmware-common
Title: Debian nonfree-touchscreen-firmware-common Manual
Author: <insert document author here>
Abstract: This manual describes what nonfree-touchscreen-firmware-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nonfree-touchscreen-firmware-common/nonfree-touchscreen-firmware-common.sgml.gz

Format: postscript
Files: /usr/share/doc/nonfree-touchscreen-firmware-common/nonfree-touchscreen-firmware-common.ps.gz

Format: text
Files: /usr/share/doc/nonfree-touchscreen-firmware-common/nonfree-touchscreen-firmware-common.text.gz

Format: HTML
Index: /usr/share/doc/nonfree-touchscreen-firmware-common/html/index.html
Files: /usr/share/doc/nonfree-touchscreen-firmware-common/html/*.html
